baseURL: http://example.org/
languageCode: en-us
title: Portfolio website for Kostis Christodoulou
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Let's Go
    subtitle: |-
      You can learn a little bit about me in my blogs. 
    title: Hi, I am Giorgi! 
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Flint Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: giorgik.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+995) 577-25-40-16 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:  
    copyright: Giorgi Keratishvili
    enable: yes
    quicklinks:
   #   - alt: HTML5 UP
  #    text: 'Design: '
   #     url: https://www.html5up.net
    social:
    #  - icon: fa-twitter
     #   label: Twitter
      #  url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/george.keratishvili
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/giorgi.keratishvili/
      - icon: fa-github
        label: GitHub
        url: https://github.com/giorgikeratishvili
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/giorgi-keratishvili-451499173/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: My Projects
        url: blogs
    button2:
    #  - name: Log In
    #    url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
   #   - name: Generic Blog
  #      url: blogs/ipsum
   #   - name: Elements
    #    url: elements.html
    menu: Menu
    subtitle: Portfolio Website
    title: Giorgi
  tiles:
    enable: yes
    showcase:
      - image: denis-arslanbekov-b-eGDk5_gPo-unsplash.jpg
        subtitle: This is where I am from 
        title: Georgia
        url: blogs/georgia
      - image: lbs.jpg
        subtitle: London Business School 
        title: Education
        url: blogs/lbs
      - image: ball.jpg
        subtitle: What I enjoy the most in my free time!
        title: Interests
        url: blogs/interest
      - image: CV.jpg
        subtitle: Check out my CV! 
        title: Curriculum Vitae
        url: blogs/cv
      - image: yield.jpg
        subtitle: R project
        title: Yield Curve Inversion
        url: blogs/yield_curve
      - image: risk.jpg
        subtitle: R project
        title: Risk-Return of DJIA stocks
        url: blogs/risk_return
#  two:
  #  buttonText: I am ready
  #  enable: yes
  #  subtitle: "If you would like to learn more about my life 
  #  you can always check out my blogs "
  #  title: Reading Blogs
  #  url: blogs
